version: "3.3"

services:
  dev_node: &dev_node
    image: node:8
    volumes:
      - "../../:/usr/src/app"
    working_dir: /usr/src/app

  node: &node
    <<: *dev_node
    entrypoint: ["node"]
    command: ["--help"]
    expose:
      - "3000"
    ports:
      - "3000:3000"

  npm:
    <<: *dev_node
    entrypoint: ["npm"]
    command: ["--help"]

  nginx:
    container_name: "frontend_nginx"
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    expose:
      - "80"
    env_file:
      - ".env"
    command: ["/bin/sh", "-c", "envsubst '$$FOO_BAR' </etc/nginx/conf.d/default.conf.template >/etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"
      - "../../public:/usr/share/nginx/html:ro"
